--Ballus, Dogfight Enforcer Q
local dm=require "expansions.utility_dmtcg"
local scard,sid=dm.GetID()
function scard.initial_effect(c)
	dm.EnableCreatureAttribute(c)
	--survivor (untap)
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(sid,0))
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
	e1:SetCode(EVENT_PHASE+PHASE_END)
	e1:SetRange(DM_LOCATION_BATTLE)
	e1:SetCondition(dm.TurnPlayerCondition(PLAYER_PLAYER))
	e1:SetTarget(dm.HintTarget)
	e1:SetOperation(dm.SelfTapUntapOperation(POS_FACEUP_UNTAPPED))
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetDescription(aux.Stringid(sid,0))
	e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
	e2:SetCode(EVENT_PHASE+PHASE_END)
	e2:SetRange(DM_LOCATION_BATTLE)
	e2:SetCondition(dm.TurnPlayerCondition(PLAYER_PLAYER))
	e2:SetTarget(dm.HintTarget)
	e2:SetOperation(dm.SelfTapUntapOperation(POS_FACEUP_UNTAPPED))
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
	e3:SetRange(DM_LOCATION_BATTLE)
	e3:SetTargetRange(LOCATION_ALL,0)
	e3:SetTarget(scard.postg)
	e3:SetLabelObject(e2)
	c:RegisterEffect(e3)
end
scard.duel_masters_card=true
function scard.postg(e,c)
	return c~=e:GetHandler() and c:DMIsRace(DM_RACE_SURVIVOR)
end
